### PR TITLE
Add GroupBy

### PR DESCRIPTION
**Pull request by AndreasInpact**
I added a GroupBy function to attach a IOmniTaskGroup to the Async Task. This gives the possibility to wait for or terminate all Async Task.

### CODE REVIEW

**Comment by vincentparrett** [comment]
I get why this might be an attractive idea, but it seems like a bit of a leaky abstraction. Currently no part of omnitasklibrary is exposed to the interface of this library, this pr would change that.  The omni library seems to be stalled/unmaintained at the moment so I would like to maintain the option to re-implement this library without the dependency in the future if needed.

**Comment by AndreasInpact** [comment]
I understand your concern, and to be honest exposing IOmniTaskGroup in the interface bothered me too. I will think of a better solution, maybe an IAwaitableGroup that uses internally a TList? Or just a wrapper around the TOmniTaskGroup?

**Comment by vincentparrett** [comment]
I would need to take a closer look at TOmniTaskGroup to see exactly what it does and how - IAwaitableGroup might be an option.

**Comment by AndreasInpact** [comment]
I replaced the IOmniTaskGroup with an implementation for IAwaitableGroup. Omni is not exposed anymore.

**Pull request merged**
